name: POSTGRES Database connectivity
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

env:
  DATABASE_NAME: testing
  DATABASE_USER: testing
  DATABASE_PASS: testing
  DATABASE_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

    # setup conatiner for postgres sql
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASS }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
